//import { Inter } from "next/font/google";
import { Libre_Baskerville } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'
import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const libre_baskerville = Libre_Baskerville({
  weight:"400",
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-libre_baskerville',

})
const libre_franklin = Libre_Franklin({
  weight:"400",
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-libre_franklin',
  
})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={libre_baskerville.variable + ' ' + libre_franklin.variable}>
        {children}
      </body>
    </html>
  );
}
